### ISSUE TITLE
Running on Mac OS is not stable.

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#29] opened 2019-08-08 03:02 UTC
Although all unit tests on Mac OS computer can be passed but the Simulation and Cov3D commands are still failed due the convergence problem. More extensive work is needed to make it more stable.

**Comment by vineetbansal** [comment] 2019-08-13 22:35
I don't believe this is true. I need to see this.

Edit: Yes..able to reproduce the issue on OS X. Will get to the bottom of this.

**Comment by garrettwrong** [comment] 2020-06-12 01:50
Maybe related to #150 . At least in that case I had an idea what was happening..

**Comment by vineetbansal** [comment] 2020-08-20 15:30
I'm closing this since #150 offers a much more comprehensive background on the issue.

**Closed as completed by vineetbansal** 2020-08-20 15:30 UTC
Labels: bug, CI, cleanup
