### ISSUE TITLE
em_classavg directory breaks pytest

### ISSUE THREAD

**Issue by garrettwrong** [ComputationalCryoEM/ASPIRE-Python#227] opened 2020-08-11 19:30 UTC
em_classavg breaks pytest collection with `ModuleNotFoundError: No module named 'data_utils'`. Example traceback is below.

In #225 we worked around it. Its currently just a pile of code sitting in the repo, so this is to be expected I guess.

```
(aspire_foo_master) ➜  ASPIRE-Python.dev git:(develop) pytest              
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.6.10, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/garrett/Dropbox/PU/aspire/ASPIRE-Python.dev, configfile: pytest.ini
plugins: cov-2.10.0
collected 178 items / 1 error / 1 deselected / 176 selected                                                                                                             

================================================================================ ERRORS =================================================================================
________________________________________________ ERROR collecting src/aspire/aspire/em_classavg/test_forward_backward.py ________________________________________________
ImportError while importing test module '/home/garrett/Dropbox/PU/aspire/ASPIRE-Python.dev/src/aspire/aspire/em_classavg/test_forward_backward.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../anaconda3/envs/aspire_foo_master/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/aspire/aspire/em_classavg/test_forward_backward.py:1: in <module>
    import data_utils
E   ModuleNotFoundError: No module named 'data_utils'
======================================================================== short test summary info ========================================================================
ERROR src/aspire/aspire/em_classavg/test_forward_backward.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================== 1 deselected, 1 error in 1.15s =====================================================================
```

**Comment by junchaoxia** [comment] 2020-08-14 15:09
Most of code under src/aspire/aspire comes from the original Python code  and has not be extracted and merged into the new framework except preprocess functions, PSWF2D basis, and orientation estimation. According current schedule we are not able to extract more in this year.  I suggest to keep them as is and try to avoid making changes since there are no systematic unit tests to ensure the changes are in right way. In this case we can reproduce corresponding results in an easier way in future.

**Comment by janden** [comment] 2020-08-14 15:15
The issue is not bringing in that code, it's just cleaning it up enough so that you can run the code without crashing. Currently `pytest` goes through all the directories and tries to run all the Python files so that it can find the tests. Fixing this is just a matter of making sure that the code runs as is.

**Comment by junchaoxia** [comment] 2020-08-14 15:54
Thanks. In the previous instruction, we try to tell the pytest running `tests` folder only. Probably we should still do it in the same way. There is no need to go through other folders since all unit tests for the new framework are under the `tests` folder.

**Comment by janden** [comment] 2020-08-14 19:00
Yes but the default invocation is `pytest`. 99% packages support this way of running `pytest` so if we don't want to scare away potential contributors (and cause headaches to ourselves, since we have all forgotten to add that extra `tests` at one point or another), let's fix this so that it runs as expected.

**Comment by junchaoxia** [comment] 2020-08-14 19:44
OK. If we want all tests under other folders working, that is great. But I am not sure those tests are ready or not since we just pulled in. If just skip them, it doesn't help too much.  But actually skipping is done in PR #225.

**Comment by janden** [comment] 2020-08-14 20:00
> But I am not sure those tests are ready or not since we just pulled in.

Well,  we don't know until we try. In general, some tests are better than no tests. Currently, nothing in `aspire.aspire` is covered. If there are some tests in there that we can use, I say let's take a look.

**Comment by junchaoxia** [comment] 2020-08-14 21:16
OK. Good to try.

**Comment by junchaoxia** [comment] 2020-10-09 20:37
The `em_classavg` folder has been removed in PR #283. Closing now.

**Closed as completed by junchaoxia** 2020-10-09 20:37 UTC
Labels: bug, CI, cleanup
