### ISSUE TITLE
mutable or immutable of ImageSource Class 

### ISSUE THREAD

**Issue by junchaoxia** [ComputationalCryoEM/ASPIRE-Python#208] opened 2020-07-17 16:31 UTC
The original design of `ImageSource` class targets an immutable class which prevents the change of class variables and metadata. However, this is not exactly followed such as in the `downsample` function that resets the class variable `L` for the image size due to the downsampling and in whitening function that modifies the type of CTF filters. The reset of `L` can cause crash in the Simulation class when the clear images need to be reconstructed at different stages. We have a few options need to be discussed.
1) Use additional variable such as `_L` for the original image size. 
2) Implement the clone method to generate new object when changing values of variables is needed. 
3) Derive new ImageSource class for each submodule or preprocess step such as the DenoisedImageSource class.

**Comment by garrettwrong** [comment] 2020-07-17 20:12
Cool, thanks for making this. Tagging @vineetbansal who will join us (next month) to chat about this.

**Comment by vineetbansal** [comment] 2020-07-21 14:28
I agree that `self.L` should not be changed by `downsample`.

The reasons that I can think of as to why it's currently doing so:
  - The `self.generation_pipeline` object (where we should be appending the `DownSample` transform, as we're also doing right now), may not be able to handle Transforms of different resolutions (I may be wrong about this).
  - The expectation by the caller that `downsample` will downsample everything about image generation (including any filters/shifts etc). This may not have been possible to do in an earlier iteration of the code, but with the `Pipeline` object it should be straightforward. Even if it works correctly in terms of generating the final images though, there's the question of whether the `metadata` associated with the the `ImageSource` should change, or should not, which we should discuss with Joakim.
  - The `Simulation` class stores all it's attributes but doesn't consult them till we ask for `_images()`, similar to the `RelionSource` class. The current behavior of changing `self.L` may simply have been a clumsy attempt to store the intention of downsampling, with the expectation that it would not be used till later. Again, with the `Pipeline` object, the `_images()` method doesn't need to know that there's a downsampling coming down the line, and it could work with the (unchanged) `self.L`.

I also strongly suggest that we disable the `cache()` method in `ImageSource` to avoid any interactions. The `Pipeline` object is designed to cache images if necessary, but we can enable that once things work correctly.

It may sound like I'm furiously defending `Pipeline`. I'm not - even if the implementation is changed, I think it's the correct abstraction to think about these these operations.

For (2):
Implement the clone method to generate new object when changing values of variables is needed.

I think a shallow copy should suffice, as long as all attributes are captured by `__init__`, so we may not have to implement anything specific to this class.

I don't quite understand (3):
Derive new ImageSource class for each submodule or preprocess step such as the DenoisedImageSource class.

One person's denoised image would be another's noisy image, so capturing past operations in a class structure doesn't make sense to me, but I might be misunderstanding something here.

**Comment by janden** [comment] 2020-07-22 21:40
Thank you for these comments, @vineetbansal. I think your second reason for why `self.L` is modified by `downsample` sounds the most likely (that we expect `downsample`, or any other preprocessing function, will modify the metadata as needed). The issue here is that `Simulation` is using these *external* variables for *internal* purposes (this split also exists for `shifts`, `rots`, `filters`, and so on, that are used to generate the images, but may be different from the ones exposed to the outside). We should try to separate these things as much as possible.

I'm not sure disabling `cache` is a good idea. It allows the user to explicitly control what's being cached and when. We can disable it temporarily, but this functionality needs to exist at some point. Pushing it into `Pipeline` carries the risk of obscuring the cache mechanism and making it harder for the user to interact with.

Regarding a new `ImageSource` class for each operation, what (I think) @junchaoxia is referring to is a functional model for sources (more like the structure of the Matlab code). In other words, instead of stacking a set of operations to be performed later (and dealing with the attendant metadata headaches). This way, a `Simulation` wouldn't have to worry about what variables are internal and external, both are identical. Then, when we apply some image processing operation (like `downsample`), this would result in a new `ImageSource` object (either through a different class or some other mechanism) that serves up the downsampled images (by calling the `images` method of its parent `Simulation` and applying the necessary downsampling) with the modified metadata. Both original `Simulation` object and this downsampled `ImageSource` would exist at the same time, the latter would refer to the former, but there would be no need to keep a list of transformations or worry about which metadata variables belong to the `Simulation` (internal) or to the downsampled `ImageSource` external.

**Comment by junchaoxia** [comment] 2020-07-30 18:52
Thanks for @vineetbansal and @janden. I believe the design of `cache` is due to some cases that we don't want to regenerate all original images through the `_images()` function of derived ImageSource classes such as Simulation and RelionImageSource. But the current `cache` implementation only works when we can load all images into memory. The `cache` function also allows us to replace the original images with an external Image object with modified images.  The design of `pipeline` mainly allows us to accumulate a series of operations on the images and only apply them on the original images (`_im`) when the `images()` is called. As discussed above the original design of ImageSource is an immutable object and we also created the  `ArrayImageSource` object to hold the images in memory. 
During the development of Cov2d module, @janden and I came out the way of derived class `DenoisedImageSource` for operations on denoised images, where `_image()`  overrides the base one to call denoising operation and generate the denoised images. This is a very similar way as the derived Simulation and RelionImageSource classes but we have new object for changed variables and metadata. This is an example of the third way listed above. In general all the preprocess steps can be done in this way so that the Simulation and RelionImageSource classes only build the original images and no variables and metadata are changed.

**Comment by garrettwrong** [comment] 2020-08-03 18:59
Adding a brief from our call today (Junchao, Vineet, Garrett present).

- Confirmed Vineet was able to build run and pass unit tests from `develop`.
- Reviewed some of the updates relating to this issue for context.
- Demonstrated this issue with Vineet.  With some clarification, we were able to reproduce the issue with Vineet.
- We discussed some of the approaches mentioned above.
- Vineet will try to focus on where exactly the resolution breaks down the subsequent pipeline steps, and may consider a potential design that will admit looping over stages in the pipeline.
- We will plan to follow up at the Aug 10 3pm meeting.

I think that is most of it, I regret not writing this earlier :). Please add anything missed.

**Comment by garrettwrong** [comment] 2020-08-04 12:19
I was going through issues this morning and noticed this may be related to #46 . If that is the case we should remember to close that one out once this is resolved.

**Comment by junchaoxia** [comment] 2021-02-09 03:09
Recently developments has tended to derived new ImageSource classes for saving denoised images and orientation angles. Hence the ImageSource class should be treated as immutable. Closing now.

**Comment by janden** [comment] 2021-02-09 13:42
> Recently developments has tended to derived new ImageSource classes for saving denoised images and orientation angles. Hence the ImageSource class should be treated as immutable. Closing now.

No the preprocessing functions still modify the object.

**Comment by garrettwrong** [comment] 2023-02-06 16:31
Was thinking about this when writing something else up. Jotting thoughts.

From practical experiences trying to perform common experimentalist and testing tasks, the Immutable model is probably the most effective path forward.  I feel that is true for both developers and scientific users.  AFAIK there is no reason we can't keep the lazy evaluation, caching, or any other features with this model.  It is good enough for numpy.... The key point of immutable for us is actually that there is only one state per source. ASPIRE's source state should match the metadata state.  (Instead of a collection of states dependent on stage of pipeline).

Some potentially complicated issues like `copy`ing #744 are natural with this model; no copy is required.  That would make interactions looks like:

```
src = Source(....)
# replace src object
src = src.method1(...)
src = src.method2(...)
# say we want to compare these later, use a new name, src is untouched
src123 = src.method3(....)
# src has methods 1,2; src123  has methods 123
```

If we strongly prefer the syntax of the current implementation we can still achieve this one state mantra by having the underlying framework return itself _before_ constructing an updated source.  Users can then decide if they want to use that variable.

```
src = Source(....)
# ignore the returns here
src.method1(...) # returns prior src, ignored
src.method2(...) # returns prior src, ignored
# say we want to compare sources later, assign the returned src
src_1_2 = src.method3(....)
# src has methods 1,2,3. while src_1_2 has 1,2
```

While the above might look contrived.. its actually a super common thing I want to do.  IE, compare an experiment applying different methods or configurations of a method.  Right now I just end up making entirely new scripts. Very manual and error prone.

Either way, I think maintaining multiple states in a source is fraught with danger. We can avoid it at the expense of duplicating a small amount (MBs) of metadata.

**Comment by garrettwrong** [comment] 2023-03-17 11:21
Started by #877 , and #866 .  Will relate to #875 .

**Comment by garrettwrong** [comment] 2023-07-06 12:17
I think this issue has mostly been settled, spare a few much smaller follow up issues. Closing

**Closed as completed by garrettwrong** 2023-07-06 12:17 UTC
Labels: bug, enhancement, question
