### ISSUE TITLE
There is a bug in "whiten" function when working with simulated source

### ISSUE THREAD

**Issue by yunpeng-shi** [ComputationalCryoEM/ASPIRE-Python#533] opened 2021-12-21 17:46 UTC
The image-whitening function is  as follows:
```python
def whiten(self, noise_filter):
        """
        Modify the `ImageSource` in-place by appending a whitening filter to the generation pipeline.
        :param noise_filter: The noise psd of the images as a `Filter` object. Typically determined by a
            NoiseEstimator class, and available as its `filter` attribute.
        :return: On return, the `ImageSource` object has been modified in place.
        """
        logger.info("Whitening source object")
        whiten_filter = PowerFilter(noise_filter, power=-0.5)

        logger.info("Transforming all CTF Filters into Multiplicative Filters")
        self.unique_filters = [
            MultiplicativeFilter(f, whiten_filter) for f in self.unique_filters
        ]
        logger.info("Adding Whitening Filter Xform to end of generation pipeline")
        self.generation_pipeline.add_xform(FilterXform(whiten_filter))
```

The last line ``self.generation_pipeline.add_xform(FilterXform(whiten_filter))`` multiplies the whitening matrix W to the noisy image y_i.  

The problem comes from the following:
The image y_i in the current code is generated by W*A_i*x_i + noise, since the CTF A_i is replaced by WA_i by the following code
```python
self.unique_filters = [
            MultiplicativeFilter(f, whiten_filter) for f in self.unique_filters
        ]
```
As a result, the whitened image is generated by W*y_i = W^2 * A_i * x_i + W*noise. This W^2 before A_i turns out to be problematic since ideally we hope  W*y_i = W * A_i * x_i + W*noise. This bug won't be detected by the testing functions, since the noise is indeed whitened. However, the power spectrum of the underlying clean signal is completely changed and will have very different scale compared to the original one.

So, the problem is that in the simulated data, the images are "whitened" twice : one from whitening of the noisy image, one from whitening of the CTF. This does not seem to be a problem for experimental data, as relion source does not generate data using the "whitened" CTF.

A fairly simple fix would be the following: 

move the following lines

```python
 logger.info("Transforming all CTF Filters into Multiplicative Filters")
        self.unique_filters = [
            MultiplicativeFilter(f, whiten_filter) for f in self.unique_filters
        ]
```
outside of the pipeline generation functions. Namely, remove these lines and add 

```python
whiten_filter = PowerFilter(noise_filter, power=-0.5)
ctf_filters = [
                MultiplicativeFilter(f, whiten_filter) for f in ctf_filters
            ]
```
whenever source.whiten() is called. Seems that the whiten function is only called in [several places](https://github.com/ComputationalCryoEM/ASPIRE-Python/search?p=2&q=whiten&type=Code) of the repository.

**Comment by garrettwrong** [comment] 2022-01-03 17:01
Hi @yunpeng-shi , thanks for reporting and providing these details.  We talked about this issue in this morning's ASPIRE meeting and @chris-langfield is going to try to reproduce the issue as you've described then work on improvements. We will keep you posted.

**Comment by chris-langfield** [comment] 2022-01-04 19:54
Thanks for the report @yunpeng-shi. I've been taking a look and will summarize the relevant information on this thread.

For future reference, I am using this paper as a guide for the intended behavior:

Bhamre, Zhang, and Singer [*Denoising and Covariance Estimation of Single Particle Cryo-EM Images*](https://arxiv.org/pdf/1602.06632.pdf) JSB (2016)

**Comment by chris-langfield** [comment] 2022-01-05 21:18
#### Reproducing the behavior using simulated data with very low white noise

This is a step by step reproduction of @yunpeng-shi's result from our email exchanges.

A `Simulation` was created with `noise_filter = ScalarFilter(dim=2, value=1.0e-10)`, and otherwise following the Cov2D tutorial. The effective filter `W` should correspond, then, to multiplying component wise by `1.0e5 = 1.0e-10 ** -0.5`. However we observe scaling by approximately `1e10`, or `W**2`. The CTF filter is not responsible for the extra scaling because it is bounded to `[-1,1]`. (The signal of the clean image is around `1.0e-1`)

It's worth noting the technicality that `W` is a scaling operator in Fourier space, but due to the linearity of the FT, we can expect the image in real space to be scaled by the same amount. This scaling would then carry on to the FB expansion, where Yunpeng noticed it.

![10e10](https://user-images.githubusercontent.com/34426450/148289534-eae3f733-5c39-431b-b013-6dc743dec4d4.png)

To confirm, change the noise to `1.0e-8`, meaning `W` is `1.0e4`. We again see scaling by `1.0e8`, or `W**2`:

![Screen Shot 2022-01-05 at 4 09 40 PM](https://user-images.githubusercontent.com/34426450/148289852-374a0225-dfd5-456b-8a5c-eb540d661f0b.png)

Noise at `1.0e-6` scales the image by `1.0e6`:

![Screen Shot 2022-01-05 at 4 13 40 PM](https://user-images.githubusercontent.com/34426450/148290351-0d65593c-db1e-4578-bb52-3181ddf9112c.png)

The reason is that, **only** in `Simulation`, the `unique_filters`, i.e. CTF filters, are applied to the data when `images()` is called:
from `Simulation._images()`:
```python
        im = self.eval_filters(im, start=start, num=num, indices=indices)
```
from `ImageSource.eval_filters()`:
```python
for i, filt in enumerate(self.unique_filters):
            idx_k = np.where(self.filter_indices[indices] == i)[0]
            if len(idx_k) > 0:
                im[idx_k] = Image(im[idx_k]).filter(filt).asnumpy()
```

So `W` is indeed being applied twice for `Simulation`s. (I also edited the issue post just to add the Python syntax highlighting)

Code used to reproduce:

```python
from aspire.source.simulation import Simulation
from aspire.operators import ScalarFilter, RadialCTFFilter
from aspire.volume import Volume
from aspire.noise import WhiteNoiseEstimator, AnisotropicNoiseEstimator
import mrcfile
import os

import numpy as np
import matplotlib.pyplot as plt

DATA_DIR = "/Users/langfield/ASPIRE-Python/gallery/tutorials/data"

img_size = 64
num_imgs = 1024
dtype=np.float32

white_noise_var = 1.0e-6
white_noise_filter = ScalarFilter(dim=2, value=white_noise_var)

pixel_size = 5 * 65 / img_size  # Pixel size of the images (in angstroms)
voltage = 200  # Voltage (in KV)
defocus_min = 1.5e4  # Minimum defocus value (in angstroms)
defocus_max = 2.5e4  # Maximum defocus value (in angstroms)
defocus_ct = 7  # Number of defocus groups.
Cs = 2.0  # Spherical aberration
alpha = 0.1  # Amplitude contrast

# Create filters
ctf_filters = [
    RadialCTFFilter(pixel_size, voltage, defocus=d, Cs=2.0, alpha=0.1)
    for d in np.linspace(defocus_min, defocus_max, defocus_ct)
]

# Load the map file of a 70S Ribosome
infile = mrcfile.open(os.path.join(DATA_DIR, "clean70SRibosome_vol_65p.mrc"))

# We prefer that our various arrays have consistent dtype.
vols = Volume(infile.data.astype(dtype) / np.max(infile.data))
vols = vols.downsample(img_size)

# Create a simulation object with specified filters and the downsampled 3D map
sim = Simulation(
    L=img_size,
    n=num_imgs,
    vols=vols,
    unique_filters=ctf_filters,
    offsets=0.0,
    amplitudes=1.0,
    dtype=dtype,
    noise_filter=white_noise_filter,
)

imgs_clean = sim.projections()
imgs_ctf_clean = sim.clean_images()
imgs_noisy = sim.images(start=0, num=num_imgs)

white_noise_estimator = WhiteNoiseEstimator(sim)
est_var_raw = white_noise_estimator.estimate()
print("Estimated noise variance prior to whitening: " + str(est_var_raw))
sim.whiten(white_noise_filter)
imgs_whitened = sim.images(start=0, num=num_imgs, enable_noise=False)
white_noise_estimator = WhiteNoiseEstimator(sim)
est_var_whitened = white_noise_estimator.estimate()
print("Estimated noise variance after whitening: " + str(est_var_whitened))

ctf_range = np.min(ctf_filters[0].evaluate_grid(sim.L)), np.max(ctf_filters[0].evaluate_grid(sim.L))
print("CTF filter range: " + str(ctf_range))

# plot the first images at different stages
idm = 0
plt.subplot(2, 2, 1)
plt.imshow(imgs_clean[idm], cmap="gray")
plt.colorbar()
plt.title("Clean")
plt.subplot(2, 2, 2)
plt.imshow(imgs_whitened[idm], cmap="gray")
plt.colorbar()
plt.title("Whitened")
plt.tight_layout()
plt.show()

```

**Comment by yunpeng-shi** [comment] 2022-01-05 21:39
Thanks @chris-langfield, for reproducing the experiments.

**Comment by garrettwrong** [comment] 2022-01-06 13:33
Awesome. Yes, thank you Chris!

**Comment by chris-langfield** [comment] 2022-01-07 18:40
I was able to run the code in my last post and get the expected scaling of the whitened image using the branch in #537. @yunpeng-shi, let us know if this solution works on your end?

Thanks

**Comment by yunpeng-shi** [comment] 2022-01-07 21:42
Thanks @chris-langfield ! It works on my end.

**Comment by garrettwrong** [comment] 2022-02-18 16:52
@chris-langfield , do you feel this okay to close now?

**Comment by chris-langfield** [comment] 2022-02-18 16:53
Yes, thanks let's close this one

**Closed as completed** 2022-02-18 16:55 UTC
Labels: bug
