### ISSUE TITLE
Broken Tutorial

### ISSUE THREAD

**Issue by j-c-c** [ComputationalCryoEM/ASPIRE-Python#705] opened 2022-09-27 19:13 UTC
`gallery/tutorials/image_expansion.py` is currently broken. This is related to the recent change of convention that `evaluate()` returns an `Image` object. 

Here is the build error:
``Unexpected failing examples:
/Users/carmichael/Work/ASPIRE-python.docs_fix_702/gallery/tutorials/image_expansion.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/carmichael/Work/ASPIRE-python.docs_fix_702/gallery/tutorials/image_expansion.py", line 59, in <module>
    fb_meanmax = np.mean(np.max(abs(fb_images - org_images), axis=(1, 2)))
TypeError: bad operand type for abs(): 'Image'
``

**Comment by garrettwrong** [comment] 2022-09-27 19:28
Closing, dupe of https://github.com/ComputationalCryoEM/ASPIRE-Python/issues/697 , which is already covered in a blocked upstream PR.

**Closed as completed by garrettwrong** 2022-09-27 19:28 UTC
Labels: bug, documentation, duplicate
