### ISSUE TITLE
Running Jupyter Notebook but aspire not found

### ISSUE THREAD

**Issue by RiceOwlXinTan** [ComputationalCryoEM/ASPIRE-Python#624] opened 2022-05-13 18:49 UTC
After installing the package and running the test, the package is able to work properly when directly calling python files eg: python abinitio_pipeline.py in aspire_env Conda environment. However, when I tried to call a jupyter notebook under aspire_env environment, the code inside cannot detect aspire pacakeg. Is there any way to address this issue?

![Screenshot 2022-05-13 133450](https://user-images.githubusercontent.com/36173011/168348036-4afb54ce-2e6b-4b17-bd43-af531145e8e9.png)
![notebook](https://user-images.githubusercontent.com/36173011/168348041-02834884-eda9-46d6-90b4-d4c63590e02d.png)

**Comment by garrettwrong** [comment] 2022-05-13 18:58
This can happen if you load Jupyter before you have loaded your conda env, or if accidentally launched outside the environment.  Changing the env in a shell with juptyer running in the bg would also behave like this for example.  Considering you successfully ran the python code directly, I would be inclined to think the `aspire` package is actually installed.  Can you double check your steps and report back?

If you are still having the same problem I can try to repro.  Thanks!

**Comment by RiceOwlXinTan** [comment] 2022-05-13 19:14
Hi,

I am indeed in aspire_env, as this is labeled in front of my command line before calling Jupiter. I am currently using the windows sub Linux system. After I call Jupiter, the browser from Linux pops up but freezes, and I have to open my windows browser to access the notebook. Do you think this might cause the issue?

**Comment by garrettwrong** [comment] 2022-05-13 19:16
Oh, I have no idea, and I'm not really setup to reproduce anything re windows....  The browser shouldn't matter though...

Sorry I didn't see the command line you are speaking about.  I will try to reproduce.

**Comment by garrettwrong** [comment] 2022-05-13 19:24
Yes, I can reproduce. Next time please include your entire traceback so we can help you faster :).

Looks like a scikit package we were using moved. I'll try to pin it down and see if we can resolve this. It is not clear why you did not see it from the python code directly.  Thank you for reporting.

**Comment by garrettwrong** [comment] 2022-05-13 19:31
Okay, I think have a fix. Please close your session then in your conda env run:

`pip install scikit-learn==1.0.2`

This will revert to the version that backed the problematic code.  Relaunch and confirm if that resolves the notebook for you.  If so I will create an issue about patching this. Thanks and sorry about the trouble.

**Comment by RiceOwlXinTan** [comment] 2022-05-13 23:47
Hi Garrett! I solved the issue. It's actually not because of scikit-learn, which I had the version you suggested. Instead, it's the  jupyter I was using. Initially, my jupyter is under /usr/bin, now I conda installed a jupyter under envs/aspire_env/bin. Thanks for your help!

**Comment by garrettwrong** [comment] 2022-05-14 00:30
Oh great! If it is useful, you can try either of these in the future to install some extra dev tools (including Jupyter, pytest etc) that might be useful working with Aspire.

`pip install "aspire[dev]"`

or, if using a local editable installation

`pip install -e ".[dev]"`

I'll close this then; thanks for reporting back.

**Closed as completed by garrettwrong** 2022-05-14 00:30 UTC
